### ISSUE TITLE
Too much space between each box

### ISSUE THREAD

**Issue by remotevase** [ImagicalDevs/Plugin-School#3]
In the "General PHP" box, there is tons of space on the top and bottom. How can we reduce that so that it's only what's needed

**Comment by Taki21** [comment]
reduce padding or margin.
ANd thx !
Dat tutorial was Beautifully Organized and designed! xD

**Comment by remotevase** [comment]
would the padding or margin be in the css files?

**Comment by Taki21** [comment]
i think if u added it in prior
