### ISSUE TITLE
[Suggestion] Clean Up File Names

### ISSUE THREAD

**Issue by Thunder33345** [ImagicalDevs/Plugin-School#8]
Honestly in my opinion the files name could do with a structure
by
ref_pluginyml.html and so on indicating that these are reference files
and for lessons
lesson(volume).(chapter).html
so first step in this case would be named
lesson1.1.html
and "Volume 3: Config, Lesson 1: Most Basic Method" would be named
lesson3.1.html
and i think genlession is good enough
this just my opinion

**Comment by remotevase** [comment]
already clean. no need to change. gets job done.

**Comment by Thunder33345** [comment]
ok i guess but the format itself is not consistent

**Comment by Chris-Prime** [comment]
*whisper* try using Laravel

**Comment by remotevase** [comment]
?
